"""Build the canonical Data Analytics report input from measured results."""
import base64
import csv
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

OUT=Path(__file__).resolve().parent
r=json.loads((OUT/'results.json').read_text())
rob=json.loads((OUT/'robustness.json').read_text())
sample=json.loads((OUT/'sample.json').read_text())
now=datetime.now(timezone.utc).isoformat()
names={'packaged':'Packaged checkpoint','local_epoch1':'Local one-epoch checkpoint'}
blocks=[]
def md(id,body,source=None):
    block=dict(id=id,type='markdown',body=body)
    if source: block['sourceId']=source
    blocks.append(block)
def photo(id,file,caption):
    encoded=base64.b64encode((OUT/file).read_bytes()).decode()
    blocks.append(dict(id=id,type='html',body=f'<figure style="margin:0"><img src="data:image/jpeg;base64,{encoded}" alt="{caption}" style="width:100%;height:auto"><figcaption>{caption}</figcaption></figure>'))

title='Segmentation checkpoint verification'
md('title','# '+title)
md('summary','## Use the packaged checkpoint for the crack prototype\n\n**The packaged `best.pt` is the stronger candidate, but full-frame drone inspection is not yet verified.** On 122 test images remaining after exact train/validation-overlap exclusion, it achieved **59.6% pooled crack-mask IoU**, versus **38.3%** for the local one-epoch checkpoint, at confidence 0.25. Both load successfully as YOLO26s segmentation models and return masks directly from images.\n\nUse `src/ml/models/weights/segmentation/best.pt` for the next prototype. Its labels are **0 = crack; 1 = pothole**, but the local training, validation, and test annotations contain only class 0. Pothole quality is unverified. The larger-road-image smoke test ran without a separate detector, but showed roadside false positives and thick masks; it cannot establish drone-video quality.')
md('comparison','## The checkpoint advantage survives overlap exclusion\n\n**IoU measures overlap, not classification accuracy:** true-positive crack pixels divided by the union of predicted and reference crack pixels, pooled across images. Higher is better. At confidence 0.25, the packaged checkpoint scores 59.6% versus 38.3% on the same 122 images (108 with reference crack pixels and 14 without). Its pixel precision is 74.1% and recall is 75.3%; the local checkpoint reaches 68.8% and 46.4%, respectively.\n\nThe chart compares pooled IoU on the exact same cohort. The **21.3 percentage-point advantage** has a paired image-bootstrap 95% percentile interval of **14.0 to 29.9 points** (2,000 resamples). This describes sampling uncertainty within this dataset, not transfer to drone footage.','clean')
blocks.append(dict(id='comparison-chart',type='chart',chartId='iou'))
md('thresholds','## Lower confidence recovers more crack pixels\n\nOn the overlap-filtered sample, lowering the packaged checkpoint threshold from 0.25 to 0.10 increases recall from 75.3% to 79.4%, with precision declining from 74.1% to 73.2%. Pooled IoU rises from 59.6% to 61.5%. This sensitivity result suggests a useful tuning direction, but **does not select a production threshold**: the same test sample was used for this comparison, and there are only 14 negative images after exclusion. The table exposes all tested thresholds rather than only the best outcome.','clean')
blocks.append(dict(id='threshold-table',type='table',tableId='thresholds'))
md('visual','## Masks can follow a crack while overstating its width\n\nThe first deterministic sample image below shows the source image, reference crack mask in green, and packaged-model output in blue. The predicted band is visibly wider than the reference on this example. **Do not treat these masks as verified crack-width or area measurements.** This diagnostic overlay includes predictions down to confidence 0.10; the headline comparison uses 0.25. The example was selected by sample order, not by its score.','images')
photo('mask-example','packaged_example_0.jpg','First sampled image: original (left), reference mask (middle), packaged prediction at confidence 0.10 (right).')
md('full-frame','## Direct image inference works; drone-frame quality remains open\n\nBoth segmentation checkpoints accepted complete stored images without a preceding detector or a damage-crop step. The training recipe resizes images to 448 pixels and uses a mixed surface-image corpus; it does not document a mandatory detector-generated crop. **This establishes that a separate detection stage is not required by the model interface.** It does not establish that the training distribution matches wide drone road frames.\n\nA separate smoke test used 32 seeded images from the preprocessed road-damage test directory, at inference sizes 448 and 736, with confidence 0.25. The packaged model returned masks on 11/32 and 19/32 images, respectively, with 14 and 30 instances. These are output counts, **not accuracy or recall**: no segmentation ground truth was evaluated for this road sample. No pothole predictions were returned. The stored images are already preprocessed; raw-frame provenance is unverified, and no video was found in the engine workspace.','road')
md('road-example-note','## Roadside structures can trigger crack predictions\n\nThe first road-sample output below includes predictions over the roadside grate and adjacent structures, a visible domain-transfer failure. The second shows a crack response while a pothole-like depression in the upper right is not segmented. These are qualitative examples at inference size 736 and confidence 0.25, not ground-truth-scored findings. They support testing representative drone frames before retiring detection on quality grounds.','images')
photo('road-example','packaged_road_0.jpg','First sampled preprocessed road image, packaged checkpoint, inference size 736, confidence 0.25.')
photo('road-example-2','packaged_road_1.jpg','Second sampled preprocessed road image, packaged checkpoint, inference size 736, confidence 0.25.')
md('checkpoint','## Checkpoint identity is verified; training completion is not\n\n**Recommended candidate:** `src/ml/models/weights/segmentation/best.pt`\n\nSHA-256: `ccbc26ac3d6ea3b9930296b65491e564c3d24461441b9bbf342287374179125f`\n\nIt is a segmentation checkpoint with labels `{0: crack, 1: pothole}`, trained with image size 448. Embedded training arguments point to a GPU run and Ultralytics 8.4.112. Its epoch field is −1, so the checkpoint alone does not establish how many epochs completed; a requested 100 epochs is not evidence of 100 completed epochs.\n\n**Comparison candidate:** `src/ml/runs/segmentation/yolo26s-crack-segmentation-6/weights/best.pt`\n\nSHA-256: `9204a4266a78029a7a5379b7ecaec72227062f8b4c2d2ddd747a5d4fd2a7b3af`\n\nThis checkpoint records epoch 0 (the first completed epoch), and its run CSV contains one epoch. Its embedded Ultralytics version is 8.4.41.\n\nThe packaged checkpoint records historical mask mAP50 of 6.16% and mAP50–95 of 1.82%; the local checkpoint records 2.59% and 0.72%. **These are saved training-validation metrics, not freshly measured test mAP.** Instance mAP penalizes instance matching and differs from the pooled binary-mask IoU measured here. The discrepancy warrants annotation and instance-definition review before production use.','checkpoints')
md('scope','## The available labels support crack evaluation only\n\nThe segmentation data contains 7,683 training images, 3,148 validation images, and 1,695 test images. There are 143,382, 59,271, and 32,088 annotated polygons, respectively; every polygon is class 0. There are 982, 395, and 221 empty label files. The conversion script explicitly assigns class 0 and converts connected mask contours into polygons. A two-class name list therefore provides no evidence of pothole supervision.\n\nThe dataset README describes images merged from 12 crack datasets and resized to 448×448, including noncrack surface images. The deterministic test draw selected 128/1,695 images with Python random seed 42: 112 had positive reference-mask pixels and 16 did not. The full-sample packaged IoU was 58.5%; the local IoU was 37.5%, both at confidence 0.25.','evaluation')
md('method','## Evaluation measures binary crack coverage at original resolution\n\n1. Load both local checkpoints with the installed Ultralytics 8.4.41 runtime and PyTorch 2.11.0. Run on CPU with four PyTorch threads; no Modal or GPU performance benchmark was performed.\n2. Infer at size 448, minimum confidence 0.10, with original-resolution masks (`retina_masks=True`). Union class-0 masks separately at thresholds 0.10, 0.25, and 0.50. Do not add engine enhancement, skeletonization, branch merging, or drone metadata.\n3. Read the paired grayscale reference mask and threshold it at greater than 127, matching the conversion script. Accumulate true-positive, false-positive, and false-negative pixels. Pixel precision = TP/(TP+FP); recall = TP/(TP+FN); IoU = TP/(TP+FP+FN). These pooled metrics weight images by their pixel contribution; they are not mean per-image IoU or instance mAP.\n4. Compute SHA-256 hashes of images across all splits; remove sampled images identical to any training or validation image. Bootstrap the paired cleaned cohort with replacement at image level, with seed 42.\n5. Preserve selected filenames, per-image pixel counts, checkpoint metadata, road-output counts, overlays, and scripts alongside this report. Median warmed local prediction-call time was about 61 ms per 448-pixel image for either checkpoint; this includes local call overhead and is not video throughput or a GPU estimate.\n\nThe installed runtime is older than the packaged checkpoint’s embedded training version. Loading and inference succeeded, but numerical parity with the original training environment has not been established.','evaluation')
md('limits','## Split contamination and domain mismatch limit the claim\n\nThere are **58 unique image hashes shared by train/test, 33 by validation/test, and 1,271 by train/validation**. Six images in the 128-image sample matched training or validation; excluding them leaves 122. Exact hashing does not detect recompressed images, overlapping crops, or different frames of the same road scene. No scene-level independence claim is made.\n\nOnly 128 test images were inferred, not the entire 1,695-image split. The bootstrap treats sampled images as independent; scene clustering could make its interval too narrow. Zero crack predictions on the 16 original negative samples is insufficient to establish a low real-world false-positive rate, especially given the road-overlay failures.\n\nPothole segmentation accuracy, raw full-road-frame accuracy, drone altitude and camera transfer, temporal stability, video reading/writing, and Modal GPU throughput remain unmeasured. The road images are preprocessed still images with unverified raw-frame provenance.','evaluation')
md('next','## Keep the simple pipeline, but separate prototype choice from release evidence\n\n1. **Use the fingerprinted packaged checkpoint for the crack-only prototype.** A Python function can pass frames directly to this segmentation model; Modal can supply GPU execution around it.\n2. **Verify full-frame quality before removing detection on performance grounds.** Annotate representative uncropped drone frames with road-only negatives, cracks at multiple apparent widths, and potholes. Compare direct segmentation with any proposed crop or tiling strategy on an untouched scene-disjoint evaluation set.\n3. **Repair the data split and confirm class supervision before retraining.** Separate by source scene, remove cross-split duplicates, audit contour-derived instance targets, and either supply pothole masks or make the model explicitly crack-only.\n4. **Tune confidence on validation data, then evaluate once on held-out scenes.** Report both pixel overlap and instance metrics, and check mask-width bias if downstream measurements matter.\n\nThe current engine configuration points to `src/ml/models/weights/yolo26s-seg.pt`, not either tested `best.pt`. The next implementation must select the verified checkpoint explicitly; model success in this report does not mean the existing engine already loads it.')
md('questions','## Evidence still needed for the next decision\n\nWhat are the intended drone altitude, camera angle, frame resolution, and smallest relevant crack width? Is pothole coverage required for the first version? Are there untouched raw videos and scene identifiers for a separate evaluation set? What recall and false-positive burden are acceptable? These answers determine whether full-frame resizing is sufficient or whether spatial tiling merits a measured comparison.')

db=sqlite3.connect(OUT/'metrics.sqlite')
db.execute('DROP TABLE IF EXISTS clean_pixels')
db.execute('CREATE TABLE clean_pixels (model TEXT, image TEXT, threshold REAL, tp INTEGER, fp INTEGER, fn INTEGER)')
raw=list(csv.DictReader((OUT/'pixel_results.csv').open()))
db.executemany('INSERT INTO clean_pixels VALUES (?,?,?,?,?,?)',[(names[x['model']],x['image'],float(x['threshold']),int(x['tp']),int(x['fp']),int(x['fn'])) for x in raw if x['image'] not in rob['excluded_images']])
sql='''SELECT model, threshold, COUNT(*) AS images,
       1.0 * SUM(tp) / SUM(tp + fp + fn) AS iou,
       1.0 * SUM(tp) / SUM(tp + fp) AS precision,
       1.0 * SUM(tp) / SUM(tp + fn) AS recall
FROM clean_pixels
GROUP BY model, threshold
ORDER BY model, threshold;'''
db.row_factory=sqlite3.Row
rows=[dict(x) for x in db.execute(sql)]
db.commit()
db.close()
(OUT/'metrics.sql').write_text(sql)
for x in rows:
    expected=next(v for v in rob['clean_summary'] if names[v['model']]==x['model'] and v['threshold']==x['threshold'])
    assert abs(x['iou']-expected['pixel_iou'])<1e-12
sources=[
 dict(id='clean',label='Overlap-filtered pixel metrics and paired bootstrap',path='reports/segmentation-check/metrics.sqlite',query=dict(sql=sql,language='sql',engine='SQLite',description='Pool per-image pixel counts after excluding six exact training or validation matches. Paired bootstrap is recorded in robustness.json.',tables_used=['main.clean_pixels'],filters=['128 seeded test images, excluding 6 exact matches to training or validation','Class 0 crack; confidence 0.10, 0.25, 0.50'],metric_definitions={'iou':'sum(TP) / sum(TP + FP + FN)','precision':'sum(TP) / sum(TP + FP)','recall':'sum(TP) / sum(TP + FN)'})),
 dict(id='evaluation',label='Evaluation results, inventory and reproducible method',path='reports/segmentation-check/results.json'),
 dict(id='checkpoints',label='Checkpoint metadata and SHA-256 fingerprints',path='reports/segmentation-check/results.json'),
 dict(id='road',label='Per-image road inference output counts',path='reports/segmentation-check/road_results.csv'),
 dict(id='images',label='Original samples and inference overlays',path='reports/segmentation-check/sample.json'),
 dict(id='docs',label='Ultralytics segmentation inference documentation',href='https://docs.ultralytics.com/tasks/segment/'),
]
artifact=dict(surface='report',manifest=dict(version=1,surface='report',title=title,generatedAt=now,blocks=blocks,sources=sources,charts=[dict(id='iou',title='Crack-mask IoU by checkpoint',subtitle='122 overlap-filtered images; confidence 0.25; pooled pixel overlap',type='bar',dataset='comparison',sourceId='clean',encodings=dict(x=dict(field='model',type='nominal',label='Checkpoint'),y=dict(field='iou',type='quantitative',label='Pooled crack-mask IoU',format='percent')),valueFormat='percent')],tables=[dict(id='thresholds',title='Confidence threshold comparison',subtitle='122 overlap-filtered images per checkpoint; metrics pooled across pixels',dataset='thresholds',sourceId='clean',defaultSort=dict(field='threshold',direction='asc'),density='spacious',columns=[dict(field='model',label='Checkpoint',type='text'),dict(field='threshold',label='Confidence',format='number'),dict(field='iou',label='IoU',format='percent'),dict(field='precision',label='Pixel precision',format='percent'),dict(field='recall',label='Pixel recall',format='percent')])]),snapshot=dict(version=1,generatedAt=now,status='ready',datasets=dict(comparison=[x for x in rows if x['threshold']==0.25],thresholds=rows)))
(OUT/'artifact.json').write_text(json.dumps(artifact,indent=2))
(OUT/'report-notes.md').write_text('Audience: technical. Delivery: portable HTML in Codex. Required roles map to title, summary, comparison/visual, scope, method/checkpoint, limits, next, questions. Visual contract: zero-baseline single-series bar for paired checkpoint IoU; threshold table for three discrete sensitivity settings; original diagnostic images embedded without editing. Native chart and table use reviewed robustness.json rows. Diagnostic images are custom HTML blocks because native quantitative charts cannot represent mask overlays. Caption identifies confidence mismatch (0.10 overlays versus 0.25 headline). No fresh mAP claimed. Full video validation not performed. Exact source identities and raw runtime metadata are preserved in the companion files.\n')
print(OUT/'artifact.json')
